"""create permissions table

Revision ID: 985bba016e64
Revises: 6dc6faaee0e2
Create Date: 2026-09-17 22:12:43.638189

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "985bba016e64"
down_revision: str | Sequence[str] | None = "6dc6faaee0e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_permissions_tenant_name"),
    )
    op.create_index(
        op.f("ix_permissions_deleted_at"), "permissions", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_permissions_tenant_id"), "permissions", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_permissions_tenant_id"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_deleted_at"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
