"""fix user roles created at default

Revision ID: a2360d9ad5d2
Revises: 1834bb2c5a09
Create Date: 2026-09-17 22:19:03.721394

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2360d9ad5d2"
down_revision: str | Sequence[str] | None = "1834bb2c5a09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_roles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_roles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text(
            "'2026-09-18 01:16:44.340855+00'::timestamp with time zone"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
