"""add_order_notes

Revision ID: a6e3de570b07
Revises: 198c8c108788
Create Date: 2026-09-19 16:48:32.534229

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6e3de570b07"
down_revision: str | Sequence[str] | None = "198c8c108788"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "notes")
    # ### end Alembic commands ###
