"""enforce tenant integrity and create ERP domain tables

Revision ID: f85b2840792a
Revises: 6f2349b54ee2
Create Date: 2026-09-17 22:40:04.419194

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f85b2840792a"
down_revision: str | Sequence[str] | None = "6f2349b54ee2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Prepare composite foreign key targets.
    op.create_unique_constraint(
        "uq_customers_tenant_id",
        "customers",
        ["tenant_id", "id"],
    )

    op.create_unique_constraint(
        "uq_permissions_tenant_id",
        "permissions",
        ["tenant_id", "id"],
    )

    op.create_unique_constraint(
        "uq_roles_tenant_id",
        "roles",
        ["tenant_id", "id"],
    )

    op.create_unique_constraint(
        "uq_roles_tenant_name",
        "roles",
        ["tenant_id", "name"],
    )

    op.create_unique_constraint(
        "uq_users_tenant_id",
        "users",
        ["tenant_id", "id"],
    )

    # Upgrade role_permissions to tenant-aware foreign keys.
    op.add_column(
        "role_permissions",
        sa.Column("tenant_id", sa.UUID(), nullable=True),
    )

    op.execute(
        """
        UPDATE role_permissions AS rp
        SET tenant_id = r.tenant_id
        FROM roles AS r
        WHERE r.id = rp.role_id
        """
    )

    op.alter_column(
        "role_permissions",
        "tenant_id",
        nullable=False,
    )

    op.create_index(
        op.f("ix_role_permissions_tenant_id"),
        "role_permissions",
        ["tenant_id"],
        unique=False,
    )

    op.drop_constraint(
        "role_permissions_permission_id_fkey",
        "role_permissions",
        type_="foreignkey",
    )

    op.drop_constraint(
        "role_permissions_role_id_fkey",
        "role_permissions",
        type_="foreignkey",
    )

    op.create_foreign_key(
        "fk_role_permissions_tenant_permission",
        "role_permissions",
        "permissions",
        ["tenant_id", "permission_id"],
        ["tenant_id", "id"],
        ondelete="CASCADE",
    )

    op.create_foreign_key(
        "fk_role_permissions_tenant_role",
        "role_permissions",
        "roles",
        ["tenant_id", "role_id"],
        ["tenant_id", "id"],
        ondelete="CASCADE",
    )

    op.create_foreign_key(
        "fk_role_permissions_tenant",
        "role_permissions",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # Upgrade user_roles to tenant-aware foreign keys.
    op.add_column(
        "user_roles",
        sa.Column("tenant_id", sa.UUID(), nullable=True),
    )

    op.execute(
        """
        UPDATE user_roles AS ur
        SET tenant_id = u.tenant_id
        FROM users AS u
        WHERE u.id = ur.user_id
        """
    )

    op.alter_column(
        "user_roles",
        "tenant_id",
        nullable=False,
    )

    op.create_index(
        op.f("ix_user_roles_tenant_id"),
        "user_roles",
        ["tenant_id"],
        unique=False,
    )

    op.drop_constraint(
        "user_roles_role_id_fkey",
        "user_roles",
        type_="foreignkey",
    )

    op.drop_constraint(
        "user_roles_user_id_fkey",
        "user_roles",
        type_="foreignkey",
    )

    op.create_foreign_key(
        "fk_user_roles_tenant_user",
        "user_roles",
        "users",
        ["tenant_id", "user_id"],
        ["tenant_id", "id"],
        ondelete="CASCADE",
    )

    op.create_foreign_key(
        "fk_user_roles_tenant_role",
        "user_roles",
        "roles",
        ["tenant_id", "role_id"],
        ["tenant_id", "id"],
        ondelete="CASCADE",
    )

    op.create_foreign_key(
        "fk_user_roles_tenant",
        "user_roles",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_id"],
            ["categories.tenant_id", "categories.id"],
            name="fk_categories_tenant_parent",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_categories_tenant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            name="uq_categories_tenant_id",
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "name",
            name="uq_categories_tenant_name",
        ),
    )

    op.create_index(
        op.f("ix_categories_deleted_at"),
        "categories",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_categories_parent_id"),
        "categories",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_categories_tenant_id"),
        "categories",
        ["tenant_id"],
        unique=False,
    )

    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "old_values",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "new_values",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "user_id"],
            ["users.tenant_id", "users.id"],
            name="fk_audit_logs_tenant_user",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_audit_logs_tenant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_audit_logs_action"),
        "audit_logs",
        ["action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"),
        "audit_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_entity_id"),
        "audit_logs",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_entity_type"),
        "audit_logs",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_tenant_id"),
        "audit_logs",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"),
        "audit_logs",
        ["user_id"],
        unique=False,
    )

    op.create_table(
        "orders",
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "total_amount",
            sa.Numeric(precision=15, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.id"],
            name="fk_orders_tenant_customer",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_orders_tenant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            name="uq_orders_tenant_id",
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "order_number",
            name="uq_orders_tenant_number",
        ),
    )

    op.create_index(
        op.f("ix_orders_customer_id"),
        "orders",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orders_deleted_at"),
        "orders",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orders_status"),
        "orders",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orders_tenant_id"),
        "orders",
        ["tenant_id"],
        unique=False,
    )

    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column(
            "price",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
        ),
        sa.Column(
            "cost_price",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "category_id"],
            ["categories.tenant_id", "categories.id"],
            name="fk_products_tenant_category",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_products_tenant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            name="uq_products_tenant_id",
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "sku",
            name="uq_products_tenant_sku",
        ),
    )

    op.create_index(
        op.f("ix_products_category_id"),
        "products",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_deleted_at"),
        "products",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_is_active"),
        "products",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_tenant_id"),
        "products",
        ["tenant_id"],
        unique=False,
    )

    op.create_table(
        "inventory",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "quantity",
            sa.Numeric(precision=15, scale=3),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "reserved_quantity",
            sa.Numeric(precision=15, scale=3),
            server_default="0",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["products.tenant_id", "products.id"],
            name="fk_inventory_tenant_product",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_inventory_tenant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "product_id",
            name="uq_inventory_tenant_product",
        ),
    )

    op.create_index(
        op.f("ix_inventory_deleted_at"),
        "inventory",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_product_id"),
        "inventory",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_tenant_id"),
        "inventory",
        ["tenant_id"],
        unique=False,
    )

    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "quantity",
            sa.Numeric(precision=15, scale=3),
            nullable=False,
        ),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
        ),
        sa.Column(
            "total_price",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["orders.tenant_id", "orders.id"],
            name="fk_order_items_tenant_order",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["products.tenant_id", "products.id"],
            name="fk_order_items_tenant_product",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_order_items_tenant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_order_items_order_id"),
        "order_items",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_items_product_id"),
        "order_items",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_items_tenant_id"),
        "order_items",
        ["tenant_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands manually adjusted ###

    op.drop_index(
        op.f("ix_order_items_tenant_id"),
        table_name="order_items",
    )
    op.drop_index(
        op.f("ix_order_items_product_id"),
        table_name="order_items",
    )
    op.drop_index(
        op.f("ix_order_items_order_id"),
        table_name="order_items",
    )
    op.drop_table("order_items")

    op.drop_index(
        op.f("ix_inventory_tenant_id"),
        table_name="inventory",
    )
    op.drop_index(
        op.f("ix_inventory_product_id"),
        table_name="inventory",
    )
    op.drop_index(
        op.f("ix_inventory_deleted_at"),
        table_name="inventory",
    )
    op.drop_table("inventory")

    op.drop_index(
        op.f("ix_products_tenant_id"),
        table_name="products",
    )
    op.drop_index(
        op.f("ix_products_is_active"),
        table_name="products",
    )
    op.drop_index(
        op.f("ix_products_deleted_at"),
        table_name="products",
    )
    op.drop_index(
        op.f("ix_products_category_id"),
        table_name="products",
    )
    op.drop_table("products")

    op.drop_index(
        op.f("ix_orders_tenant_id"),
        table_name="orders",
    )
    op.drop_index(
        op.f("ix_orders_status"),
        table_name="orders",
    )
    op.drop_index(
        op.f("ix_orders_deleted_at"),
        table_name="orders",
    )
    op.drop_index(
        op.f("ix_orders_customer_id"),
        table_name="orders",
    )
    op.drop_table("orders")

    op.drop_index(
        op.f("ix_audit_logs_user_id"),
        table_name="audit_logs",
    )
    op.drop_index(
        op.f("ix_audit_logs_tenant_id"),
        table_name="audit_logs",
    )
    op.drop_index(
        op.f("ix_audit_logs_entity_type"),
        table_name="audit_logs",
    )
    op.drop_index(
        op.f("ix_audit_logs_entity_id"),
        table_name="audit_logs",
    )
    op.drop_index(
        op.f("ix_audit_logs_created_at"),
        table_name="audit_logs",
    )
    op.drop_index(
        op.f("ix_audit_logs_action"),
        table_name="audit_logs",
    )
    op.drop_table("audit_logs")

    op.drop_index(
        op.f("ix_categories_tenant_id"),
        table_name="categories",
    )
    op.drop_index(
        op.f("ix_categories_parent_id"),
        table_name="categories",
    )
    op.drop_index(
        op.f("ix_categories_deleted_at"),
        table_name="categories",
    )
    op.drop_table("categories")

    op.drop_constraint(
        "fk_user_roles_tenant",
        "user_roles",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_user_roles_tenant_role",
        "user_roles",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_user_roles_tenant_user",
        "user_roles",
        type_="foreignkey",
    )

    op.drop_index(
        op.f("ix_user_roles_tenant_id"),
        table_name="user_roles",
    )

    op.drop_column(
        "user_roles",
        "tenant_id",
    )

    op.create_foreign_key(
        "user_roles_role_id_fkey",
        "user_roles",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "user_roles_user_id_fkey",
        "user_roles",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_constraint(
        "fk_role_permissions_tenant",
        "role_permissions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_role_permissions_tenant_role",
        "role_permissions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_role_permissions_tenant_permission",
        "role_permissions",
        type_="foreignkey",
    )

    op.drop_index(
        op.f("ix_role_permissions_tenant_id"),
        table_name="role_permissions",
    )

    op.drop_column(
        "role_permissions",
        "tenant_id",
    )

    op.create_foreign_key(
        "role_permissions_role_id_fkey",
        "role_permissions",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "role_permissions_permission_id_fkey",
        "role_permissions",
        "permissions",
        ["permission_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_constraint(
        "uq_users_tenant_id",
        "users",
        type_="unique",
    )
    op.drop_constraint(
        "uq_roles_tenant_name",
        "roles",
        type_="unique",
    )
    op.drop_constraint(
        "uq_roles_tenant_id",
        "roles",
        type_="unique",
    )
    op.drop_constraint(
        "uq_permissions_tenant_id",
        "permissions",
        type_="unique",
    )
    op.drop_constraint(
        "uq_customers_tenant_id",
        "customers",
        type_="unique",
    )

    # ### end Alembic commands ###
